version: 2.1


parameters:
  browser:
    type: string
    default: "chrome"

jobs:
  build:
    docker:
      - image: cypress/included:12.6.0
    steps:
      - checkout
      - run: npm install
      - run: 
          name: Run tests on ${{ parameters.browser }} browser
          command: npx cypress run --browser ${{ parameters.browser }}
          environment:
            browser: ${{ parameters.browser }}
          when: always

workflows:
  version: 2
  build:
    jobs:
     - build


