version: 2.1

parameters:
  browser:
    type: string
    default: "chrome"

jobs:
  build:
    docker:
      - image: cypress/included:12.6.0
    steps:
      - checkout
      - run: npm install
    test:
     environment:
      BROWSER: << pipeline.parameters.browser >>  
    steps:
      - run: npx cypress run --browser ${BROWSER}


workflows:
  build:
    jobs:
      - build
      - test
