version: 2.1

parameters:
  browser:
    type: string
    default: "chrome"

jobs:
  test:
    docker:
      - image: cypress/included:12.6.0
    environment:
      BROWSER: << pipeline.parameters.browser >>  
    steps:
      - checkout
      - run: npm install
      - run: npx cypress run --browser ${BROWSER}
      - store_test_results:
          path: test-results
workflows:
  build:
    jobs:
      - test
