version: 2.1

orbs:
  cypress: cypress-io/cypress@1.4.0

jobs:
  build:
    executor: cypress/default
    steps:
      - checkout
      - cypress/install
      - run: npx cypress run

workflows:
  version: 2
  build:
    jobs:
      - build
