version: 2.1


parameters:
  browser:
    type: string
    default: "chrome"

jobs:
  build:
    docker:
      - image: cypress/included:12.6.0
    steps:
      - checkout
      - run: npm install
      - run: npx cypress run --browser $browser
        environment:
          browser: ${{ parameters.browser }}

workflows:
  version: 2
  build:
    jobs:
     - build


