version: 2.1

jobs:
  build:
    docker:
      - image: cypress/included:12.6.0
    steps:
      - checkout
      - run: npm install
      - run: npx cypress run --browser $BROWSER

workflows:
  version: 2
  build:
    jobs:
      - build

