version: 2.1

jobs:
  build:
    docker:
      - image: cypress/included:12.6.0
    steps:
      - checkout
      - run: npm install
      - run: |
          if [ "$BROWSER" = "chrome" ]; then
            npx cypress run --browser chrome
          else
            npx cypress run
          fi

workflows:
  version: 2
  build:
    jobs:
      - build:
          environment:
            BROWSER: $BROWSER
